### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by DirkHeinke** [emergent-interfaces/open-playout#3]
Hi,

just noted there is no license for this repo. Is it MIT?

Would be nice if you could add one.

**Comment by superlou** [comment]
Sorry about that.  I would personally lean GPL, as I was hoping to use it to make some typically inaccessible tools more available for education or public access use.  Is there a particular kind of project you are interested in?

**Comment by DarkDirk** [comment]
I can't help you to decide which license to chose, but I don't like the whole copyleft stuff. But here may be the wrong place to discuss it. So if you're interested in what project I'm planning, please write me mail.

**Comment by superlou** [comment]
Will continue conversation via email and update this issue when more information is available.

**Comment by superlou** [comment]
Licensing under GPLv3.
